version: '3'

services:
  db:
    image: mysql:5.7
    restart: always # The on-failure policy restarts a container if the exit code indicates an on-failure error.
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db # creates db database
      MYSQL_USER: admin # for your application so you don't need to use root
      MYSQL_PASSWORD: pass # for your application so you don't need to use root
    # ports:
    # - "9906:3306" # we don't need to expose this to host because phpmyadmin and web services are on the same guest network.

  web:
    build: . # docker build .
    restart: always
    depends_on:
    - db
    volumes:
    - ./app/:/var/www/html/ # real time sync between host:guest folders
    ports:
    - "8080:80"
    # stdin_open: true # docker exec -i <container name> bash; shell access enabled for container
    # tty: true # docker exec -t <container name> bash; shell access enabled for container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
    - db
    ports:
    - "8088:80"